server:
  port: 8080
  servlet:
    context-path: /enrollment

spring:
  liquibase:
    drop-first: true
  datasource:
    url: jdbc:postgresql://database-2.carx3wwmsi6k.us-east-1.rds.amazonaws.com:5432/enrollment
    username: enrollment_user
    password: tempPass123
  jpa:
    hibernate:
      show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE